
version: '3.8'

services:
  backend:
    build: ./odev
    ports:
      - "5001:5000"
    volumes:
      - ./odev:/time
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
